app = "church-tracker"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    type = "http"
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/recent"

[env]
  PORT = "8000"
