name: hourly-update
on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Collect RSS
        run: python pipelines/rss_collect.py
      - name: Collect YouTube
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python pipelines/youtube_collect.py
      - name: Normalize
        run: python pipelines/normalize.py
      - name: Build DB + vectors
        run: |
          python - <<'PY'
          from app.store import init, load_processed, init_vectors, upsert_vectors
          c = init(); load_processed(c); coll = init_vectors(); upsert_vectors(coll)
          print("DB + vectors ready")
          PY
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tracker-artifacts
          path: |
            tracker.db
            .chroma/
            data/processed/
