name: on-demand-snapshot

on:
  workflow_dispatch: {}    # manual run only

permissions:
  contents: write

concurrency:
  group: on-demand-snapshot
  cancel-in-progress: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python pipelines/rss_collect.py
      - env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          if [ -n "${{ secrets.YOUTUBE_API_KEY }}" ]; then
            python pipelines/youtube_collect.py || echo "[warn] YouTube failed; continuing..."
          else
            echo "[info] YOUTUBE_API_KEY not set; skipping YouTube collection."
          fi
      - run: python pipelines/normalize.py
      - run: |
          python - <<'PY'
          from app.store import init, load_processed, init_vectors, upsert_vectors
          c = init(); load_processed(c); coll = init_vectors(); upsert_vectors(coll)
          print("DB + vectors ready")
          PY
      - run: |
          mkdir -p dist
          TS=$(date -u +%Y%m%d-%H%M)
          TAG="data-${TS}"
          zip -r "dist/tracker-artifacts-${TAG}.zip" tracker.db .chroma data/processed || true
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: tracker-artifacts
          path: dist/*.zip
          retention-days: 7
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: "Church tracker data – ${{ env.TAG }}"
          body: "Manual snapshot."
          files: dist/*.zip
